// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  return $("#button").click(function() {
    var toAdd;
    toAdd = $("input[name=checkListItem]").val();
    $(".list").append("<div class='item'>" + toAdd + "</div>");
    return $("input").val("");
  });
});

$(document).on("click", ".item", function() {
  return $(this).remove();
});
