// Generated by CoffeeScript 1.8.0
var end, reactor, singleDigitals, start, status, _i, _j, _results, _results1;

status = "normal";

reactor = "primed";

if (status === "normal") {
  console.log("All clear");
}

if (reactor !== "primed") {
  console.log("Abort mission");
}

singleDigitals = (function() {
  _results = [];
  for (_i = 0; _i <= 100; _i++){ _results.push(_i); }
  return _results;
}).apply(this);

start = 5;

end = 9999;

singleDigitals = (function() {
  _results1 = [];
  for (var _j = start; start <= end ? _j < end : _j > end; start <= end ? _j++ : _j--){ _results1.push(_j); }
  return _results1;
}).apply(this);
