// Generated by CoffeeScript 1.8.0
(function() {
  var nameElement, shop, threeSquared;

  threeSquared = Math.pow(3, Math.floor(Math.min(4, Math.sqrt(5))));

  shop = {
    owner: {
      name: "Jesus " + threeSquared
    }
  };

  nameElement = document.getElementById("owner_name");

  nameElement.innerHTML = shop.owner.name;

  console.log("hello, Jesus");


  /*
  this is a lot of comments
   */

}).call(this);
